// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxhxRqtRU2Z6wHviqZAb3zxtQOOhgDDrY',
    appId: '1:430820266411:web:c97dbcdbb445f2dd9e42ee',
    messagingSenderId: '430820266411',
    projectId: 'e-learning-app-ddf1f',
    authDomain: 'e-learning-app-ddf1f.firebaseapp.com',
    storageBucket: 'e-learning-app-ddf1f.appspot.com',
    measurementId: 'G-FM6MN2B6V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JdEgTB69Fo5QnljqoOQPqoQX92JGfeI',
    appId: '1:430820266411:android:ddd967160a939bba9e42ee',
    messagingSenderId: '430820266411',
    projectId: 'e-learning-app-ddf1f',
    storageBucket: 'e-learning-app-ddf1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4pC-V-Yn77hBUZEW8c7kzDvcLAP7-lLI',
    appId: '1:430820266411:ios:b2aba80ab0da461e9e42ee',
    messagingSenderId: '430820266411',
    projectId: 'e-learning-app-ddf1f',
    storageBucket: 'e-learning-app-ddf1f.appspot.com',
    iosBundleId: 'com.project.E_learningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4pC-V-Yn77hBUZEW8c7kzDvcLAP7-lLI',
    appId: '1:430820266411:ios:b2aba80ab0da461e9e42ee',
    messagingSenderId: '430820266411',
    projectId: 'e-learning-app-ddf1f',
    storageBucket: 'e-learning-app-ddf1f.appspot.com',
    iosBundleId: 'com.project.E_learningapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxhxRqtRU2Z6wHviqZAb3zxtQOOhgDDrY',
    appId: '1:430820266411:web:69254703330ea18b9e42ee',
    messagingSenderId: '430820266411',
    projectId: 'e-learning-app-ddf1f',
    authDomain: 'e-learning-app-ddf1f.firebaseapp.com',
    storageBucket: 'e-learning-app-ddf1f.appspot.com',
    measurementId: 'G-PSRYER6TRH',
  );
}
